name: weather_report
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  build_runner: any
  retrofit: 3.0.1+1
  shimmer: 2.0.0
  flutter_svg: 1.1.6
  flutter_svg_provider: 1.0.3
  dio: 4.0.6
  dio_cache_interceptor: 3.3.1
  darq: 1.2.1
  json_annotation: 4.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_lints: ^2.0.0
  freezed: ^2.3.2  
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  retrofit_generator: ^4.0.3+1

flutter:
  uses-material-design: true
  assets:    
    - lib/assets/images/    
    - lib/assets/svg/    
    - lib/assets/icons/
    - lib/assets/environments/.env
